#publish_topic_names:
#    reference_pointcloud_publish_topic: ''
#    aligned_pointcloud_publish_topic: ''
#    localization_detailed_publish_topic: ''
#    localization_diagnostics_publish_topic: '' 
#    localization_times_publish_topic: ''


filters:
    reference_pointcloud:
        1_pass_through_x:
            pass_through_field_name: 'x'
            pass_through_min_value: -5.387
            pass_through_max_value: 3.001
            pass_through_filtered_cloud_publish_topic: ''
        2_pass_through_y:
            pass_through_field_name: 'y'
            pass_through_min_value: -4.181
            pass_through_max_value: 8.207
            pass_through_filtered_cloud_publish_topic: ''
        3_voxel_grid:
            leaf_size_x: 0.01
            leaf_size_y: 0.01
            leaf_size_z: 0.01
            filter_limit_field_name: 'z'
            filter_limit_min: -0.001
            filter_limit_max: 1.8
            voxel_grid_filtered_cloud_publish_topic: ''
            downsample_all_data: false
            save_leaf_layout: false
    ambient_pointcloud:
        1_voxel_grid:
            leaf_size_x: 0.05
            leaf_size_y: 0.05
            leaf_size_z: 0.05
            filter_limit_field_name: 'z'
            filter_limit_min: -1.001
            filter_limit_max: 1.8
            voxel_grid_filtered_cloud_publish_topic: ''
            downsample_all_data: false
            save_leaf_layout: false


cloud_matchers:
    ignore_height_corrections: false
    point_matchers:
        iterative_closest_point:
            max_correspondence_distance: 0.05                    # overrides parent
            transformation_epsilon: 1e-3                        # overrides parent
            euclidean_fitness_epsilon: 1e-3                     # overrides parent
            max_number_of_registration_iterations: 500          # overrides parent
            max_number_of_ransac_iterations: 500                # overrides parent
            ransac_outlier_rejection_threshold: 0.05            # overrides parent
            match_only_keypoints: false                         # overrides parent
            display_cloud_aligment: false                       # overrides parent
            maximum_number_of_displayed_correspondences: 0      # overrides parent
            use_reciprocal_correspondences: true


outlier_detectors:
    euclidean_outlier_detector:
        max_inliers_distance: 0.02
        aligned_pointcloud_outliers_publish_topic: 'aligned_pointcloud_outliers'


transformation_validators:
    pose_tracking_timeout: 2.0
    euclidean_transformation_validator:
        max_transformation_angle: 0.4
        max_transformation_distance: 0.025
        max_new_pose_diff_angle: 0.6
        max_new_pose_diff_distance: 0.2
        max_alignment_fitness: 1.0
        max_outliers_percentage: 0.6
