#normal_estimators:
#    ambient_pointcloud:
#        display_normals: false
#        normal_estimation_omp:
#            search_k: 7
#            search_radius: 0.12
#
#
#keypoint_detectors:
#    ambient_pointcloud:
#        intrinsic_shape_signature_3d:
#            salient_radius: 0.14
#            non_max_radius: 0.08
#            normal_radius: 0.08
#            border_radius: 0.0
#            threshold21: 0.975
#            threshold32: 0.975
#            min_neighbors: 5
#            angle_threshold: 1.57
#            iss3d_keypoints_cloud_publish_topic: 'ambient_keypoints'
#        sift_3d:
#            min_scale: 0.01
#            number_octaves: 3
#            number_scales_per_octave: 4
#            min_contrast: 0.001
#            sift3d_keypoints_cloud_publish_topic: 'ambient_keypoints'
