#normal_estimators:
#    reference_pointcloud:
#        display_normals: false
#        display_occupancy_grid_pointcloud: false
#        flip_normals_using_occupancy_grid_analysis: true
#        occupancy_grid_analysis_radius_resolution_percentage: 4.0
#        normal_estimator_sac:
#            model_type: 'SACMODEL_LINE'
#            method_type: 'SAC_RANSAC'
#            inlier_distance_threshold: 0.025
#            max_iterations: 50
#            sac_termination_probability: 0.99
#            optimize_coefficients: true
#            min_model_radius: -1.0
#            max_model_radius: -1.0
#            random_samples_max_k: 0
#            random_samples_max_radius: 0.15
#            minimum_inliers_percentage: 0.5
#    ambient_pointcloud:
#        display_normals: false
#        normal_estimator_sac:
#            model_type: 'SACMODEL_LINE'
#            method_type: 'SAC_RANSAC'
#            inlier_distance_threshold: 0.025
#            max_iterations: 50
#            sac_termination_probability: 0.99
#            optimize_coefficients: true
#            min_model_radius: -1.0
#            max_model_radius: -1.0
#            random_samples_max_k: 0
#            random_samples_max_radius: 0.15
#            minimum_inliers_percentage: 0.5
#
#
#curvature_estimators:
#    reference_pointcloud:
#        principal_curvatures_estimation:
#            search_k: 0
#            search_radius: 0.15
#            curvature_type: 'CURVATURE_TYPE_MEAN'
#            update_normals_with_principal_component_directions: false
#    ambient_pointcloud:
#        principal_curvatures_estimation:
#            search_k: 0
#            search_radius: 0.15
#            curvature_type: 'CURVATURE_TYPE_MEAN'
#            update_normals_with_principal_component_directions: false
#
#
#keypoint_detectors:
#    reference_pointcloud:
#        sift_3d:
#            min_scale: 0.01
#            number_octaves: 3
#            number_scales_per_octave: 4
#            min_contrast: 0.007
#            sift3d_keypoints_cloud_publish_topic: 'reference_keypoints'
##        intrinsic_shape_signature_3d:
##            salient_radius: 0.14
##            non_max_radius: 0.08
##            normal_radius: 0.08
##            border_radius: 0.0
##            threshold21: 0.975
##            threshold32: 0.975
##            min_neighbors: 5
##            angle_threshold: 1.57
##            iss3d_keypoints_cloud_publish_topic: 'reference_keypoints'
#    ambient_pointcloud:
#        sift_3d:
#            min_scale: 0.01
#            number_octaves: 3
#            number_scales_per_octave: 4
#            min_contrast: 0.007
#            sift3d_keypoints_cloud_publish_topic: 'ambient_keypoints'
##        intrinsic_shape_signature_3d:
##            salient_radius: 0.14
##            non_max_radius: 0.08
##            normal_radius: 0.08
##            border_radius: 0.0
##            threshold21: 0.975
##            threshold32: 0.975
##            min_neighbors: 5
##            angle_threshold: 1.57
##            iss3d_keypoints_cloud_publish_topic: 'ambient_keypoints'


initial_pose_estimators_matchers:
    point_matchers:
#        iterative_closest_point:
        iterative_closest_point_non_linear:
            max_correspondence_distance: 10.0
            transformation_epsilon: 1e-4
            euclidean_fitness_epsilon: 1e-4
            max_number_of_registration_iterations: 350
            max_number_of_ransac_iterations: 350
            ransac_outlier_rejection_threshold: 0.05
            match_only_keypoints: false
            display_cloud_aligment: false
            maximum_number_of_displayed_correspondences: 0
            use_reciprocal_correspondences: true
