normal_estimators:
    reference_pointcloud:
        display_normals: false
        display_occupancy_grid_pointcloud: false
        flip_normals_using_occupancy_grid_analysis: true
        occupancy_grid_analysis_radius_resolution_percentage: 4.0
        normal_estimator_sac:
            model_type: 'SACMODEL_LINE'
            method_type: 'SAC_RANSAC'
            inlier_distance_threshold: 0.65
            max_iterations: 50
            sac_termination_probability: 0.99
            optimize_coefficients: true
            min_model_radius: -1.0
            max_model_radius: -1.0
            random_samples_max_k: 0
            random_samples_max_radius: 0.65
            minimum_inliers_percentage: 0.5
    ambient_pointcloud:
        compute_normals_when_tracking_pose: true
        compute_normals_when_recovering_pose_tracking: true
        compute_normals_when_estimating_initial_pose: true
        display_normals: false
        normal_estimator_sac:
            model_type: 'SACMODEL_LINE'
            method_type: 'SAC_RANSAC'
            inlier_distance_threshold: 0.65
            max_iterations: 50
            sac_termination_probability: 0.99
            optimize_coefficients: true
            min_model_radius: -1.0
            max_model_radius: -1.0
            random_samples_max_k: 0
            random_samples_max_radius: 0.65
            minimum_inliers_percentage: 0.5


curvature_estimators:
    reference_pointcloud:
        principal_curvatures_estimation:
            search_k: 0
            search_radius: 0.65
            curvature_type: 'CURVATURE_TYPE_MEAN'
            update_normals_with_principal_component_directions: false
    ambient_pointcloud:
        principal_curvatures_estimation:
            search_k: 0
            search_radius: 0.65
            curvature_type: 'CURVATURE_TYPE_MEAN'
            update_normals_with_principal_component_directions: false


tracking_matchers:
    ignore_height_corrections: false
    use_internal_tracking: true
    pose_tracking_timeout: 2.0
    point_matchers:
#        iterative_closest_point:
        iterative_closest_point_2d:
#        iterative_closest_point_non_linear:
#        iterative_closest_point_generalized:
            max_correspondence_distance: 2.5
            transformation_epsilon: 1e-6
            euclidean_fitness_epsilon: 1e-6
            max_number_of_registration_iterations: 500
            max_number_of_ransac_iterations: 500
            ransac_outlier_rejection_threshold: 0.035
            match_only_keypoints: false
            display_cloud_aligment: false
            maximum_number_of_displayed_correspondences: 0
            rotation_epsilon: 0.002
            correspondence_randomness: 50
            maximum_optimizer_iterations: 100
            use_reciprocal_correspondences: true


outlier_detectors:
    euclidean_outlier_detector:
        max_inliers_distance: 0.07
        aligned_pointcloud_outliers_publish_topic: 'aligned_pointcloud_outliers'
        aligned_pointcloud_inliers_publish_topic: 'aligned_pointcloud_inliers'


cloud_analyzers:
    compute_inliers_angular_distribution: true
    compute_outliers_angular_distribution: true
    angular_distribution_analyzer:
        number_of_angular_bins: 180


transformation_validators:
    euclidean_transformation_validator:
        max_transformation_angle: 0.4
        max_transformation_distance: 0.3
        max_new_pose_diff_angle: 1.1
        max_new_pose_diff_distance: 0.8
        max_root_mean_square_error: 0.035
        max_outliers_percentage: 0.35
