cloud_matchers:
    ignore_height_corrections: false
    pose_tracking_timeout: 2.0
    point_matchers:
        iterative_closest_point:
#        iterative_closest_point_non_linear:
            max_correspondence_distance: 0.02
            transformation_epsilon: 1e-4
            euclidean_fitness_epsilon: 1e-4
            max_number_of_registration_iterations: 50
            max_number_of_ransac_iterations: 50
            ransac_outlier_rejection_threshold: 0.05
            match_only_keypoints: false
            display_cloud_aligment: false
            maximum_number_of_displayed_correspondences: 0
            use_reciprocal_correspondences: true


outlier_detectors:
    euclidean_outlier_detector:
        max_inliers_distance: 0.01
        aligned_pointcloud_outliers_publish_topic: 'aligned_pointcloud_outliers'


transformation_validators:
    euclidean_transformation_validator:
        max_transformation_angle: 0.1
        max_transformation_distance: 0.02
        max_new_pose_diff_angle: 0.5
        max_new_pose_diff_distance: 0.05
        max_alignment_fitness: 0.005
        max_outliers_percentage: 0.05
